2017-06-09T07:39:50+0000 [-] unauthorized login: 
2017-06-09T07:39:50+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,13813,195.22.127.83] 'root' trying auth 'password'
2017-06-09T07:39:52+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,13813,195.22.127.83] login attempt: 26496
2017-06-09T07:39:52+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,13813,195.22.127.83] login return, expect: [support/support]
2017-06-09T07:39:54+0000 [SSHService 'ssh-userauth' on HoneyPotSSHTransport,13813,195.22.127.83] login attempt [root/dreambox] failed
2017-06-09T07:39:54+0000 [HoneyPotSSHTransport,13813,195.22.127.83] connection lost
2017-06-09T07:39:54+0000 [HoneyPotSSHTransport,13813,195.22.127.83] Connection lost after 68 seconds
2017-06-09T07:39:55+0000 [-] 'root' failed auth 'password'
2017-06-09T07:39:55+0000 [-] unauthorized login: 
2017-06-09T07:39:55+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:
2017-06-09T07:39:55+0000 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
	    self._startRunCallbacks(result)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/ssh/userauth.py", line 251, in _ebBadAuth
	    NS(b','.join(self.supportedAuthentications)) + b'\x00')
	  File "/home/cowrie/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/conch/ssh/transport.py", line 637, in sendPacket
	    self.transport.write(encPacket)
	exceptions.AttributeError: 'NoneType' object has no attribute 'write'
	
2017-06-09T07:40:01+0000 [CowrieTelnetTransport,31795,109.236.83.229] Connection lost after 132 seconds
